"""order add executor_id

Revision ID: 9cc4b7456366
Revises: b376336d4e35
Create Date: 2026-05-16 20:31:20.101212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc4b7456366'
down_revision: Union[str, Sequence[str], None] = 'b376336d4e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('executor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['executor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'executor_id')
    # ### end Alembic commands ###
