"""bid uniq owner_id and order_id

Revision ID: b376336d4e35
Revises: f0f6882cbcd7
Create Date: 2026-05-16 20:03:06.419875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b376336d4e35'
down_revision: Union[str, Sequence[str], None] = 'f0f6882cbcd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_bid_owner_order', 'bids', ['owner_id', 'order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_bid_owner_order', 'bids', type_='unique')
    # ### end Alembic commands ###
