"""rename images_ulr

Revision ID: cc670cf14327
Revises: e947895c5506
Create Date: 2026-05-18 14:47:54.713812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc670cf14327'
down_revision: Union[str, Sequence[str], None] = 'e947895c5506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images_order', sa.Column('image_url', sa.String(), nullable=False))
    op.drop_column('images_order', 'images_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images_order', sa.Column('images_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('images_order', 'image_url')
    # ### end Alembic commands ###
