"""add images_order relationship

Revision ID: e947895c5506
Revises: 1658dd60e72c
Create Date: 2026-05-18 14:46:09.930355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e947895c5506'
down_revision: Union[str, Sequence[str], None] = '1658dd60e72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images_order', sa.Column('images_url', sa.String(), nullable=False))
    op.drop_column('images_order', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images_order', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('images_order', 'images_url')
    # ### end Alembic commands ###
